version: '3'
services:
  flask_app_1:
    build: ./Flask 1
    ports:
      - "5001:5000"
    volumes:
      - ./flask1:/app
  flask_app_2:
    build: ./Flask 2
    ports:
      - "5002:5000"
    volumes:
      - ./flask2:/app




    